### ISSUE TITLE
Have the possibility to add the ADSENSE_CLIENT token through a param to adsense()

### ISSUE THREAD

**Issue by pt-br** [guoyunhe/vite-plugin-adsense#1]
Hi there!

First and foremost, thank you for creating the plugin, it works very well.

It would be very interesting if it could have the possibility to pass the token directly through a parameter on vite.config.

In my scenario for example, what would be useful for the i18n versions of my website, as I have different ad sense clients and analytics tokens.

example with the VitePluginRadar:

```
VitePluginRadar({
        analytics: {
          id: LOCALE === 'pt' ? 'G-XXXX' : 'G-XXXX',
        },
      }),
```

**Comment by pt-br** [comment]
I just noticed that this is already supported.

So maybe a quick update to the readme file should help others to find out this easily in the future! 😄

**Comment by guoyunhe** [comment]
Thanks for pointing out the doc issue! I have updated the README. Hope it is clear enough :smile:
